services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "341105"
      MYSQL_DATABASE: "myDB"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "341105"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
